plugins:
 - jekyll-relative-links
relative_links:
 enabled: true
 collections: true
include:
 - README.md
 - userguide.md
 - programmingguide.md
 - configurablepanel.md
 - uiproperty.md
 - uiparameter.md
 - internalproperty.md
 - configurablemainframe.md
 - plugin.md
 - usingeclipse.md
 - installation.md
 - jcomponents.md
 - img/menu-congif.png

theme: jekyll-theme-slate
