package de.embl.rieslab.simpleui;

import java.util.HashMap;
import java.util.TreeMap;

import javax.swing.JFrame;

import de.embl.rieslab.emu.controller.SystemController;
import de.embl.rieslab.emu.ui.ConfigurableMainFrame;
import de.embl.rieslab.emu.utils.settings.Setting;

public class SimpleFrame extends ConfigurableMainFrame {

	private static final long serialVersionUID = 1L;

	/**
	 * Create the frame.
	 */
	public SimpleFrame(String title, SystemController controller, TreeMap<String, String> pluginSettings) {
		super(title, controller, pluginSettings);
	}

	@Override
	protected void initComponents() {
		/*
		 * All the initialization of the components should be done here.
		 * If the code was generated by a drag and drop software, then
		 * the code should be moved here. 
		 */ 
		setBounds(100, 100, 420, 382);
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		getContentPane().setLayout(null);
	
		FilterWheelPanel filterWheelPanel = new FilterWheelPanel("FilterWheel");
		filterWheelPanel.setBounds(10, 259, 382, 54);
		getContentPane().add(filterWheelPanel);
		
		LaserPanel laserPanel = new LaserPanel("Laser0");
		laserPanel.setBounds(10, 11, 116, 245);
		getContentPane().add(laserPanel);
		
		LaserPanel laserPanel_1 = new LaserPanel("Laser1");
		laserPanel_1.setBounds(147, 11, 116, 245);
		getContentPane().add(laserPanel_1);
		
		LaserPanel laserPanel_2 = new LaserPanel("Laser2");
		laserPanel_2.setBounds(276, 11, 116, 245);
		getContentPane().add(laserPanel_2);
	}

	@Override
	public HashMap<String, Setting> getDefaultPluginSettings() {
		return new HashMap<String, Setting>();
	}
}
